window.esdocSearchIndex = [
  [
    "neo4jay/lib/cypher.js~cypher",
    "class/lib/cypher.js~Cypher.html",
    "<span>Cypher</span> <span class=\"search-result-import-path\">Neo4Jay/lib/cypher.js</span>",
    "class"
  ],
  [
    "neo4jay/lib/model.js~model",
    "class/lib/model.js~Model.html",
    "<span>Model</span> <span class=\"search-result-import-path\">Neo4Jay/lib/model.js</span>",
    "class"
  ],
  [
    "neo4jay/lib/node.js~node",
    "class/lib/node.js~Node.html",
    "<span>Node</span> <span class=\"search-result-import-path\">Neo4Jay/lib/node.js</span>",
    "class"
  ],
  [
    "neo4jay/lib/errors.js~notfounderror",
    "class/lib/errors.js~NotFoundError.html",
    "<span>NotFoundError</span> <span class=\"search-result-import-path\">Neo4Jay/lib/errors.js</span>",
    "class"
  ],
  [
    "neo4jay/lib/schema.js~schema",
    "class/lib/schema.js~Schema.html",
    "<span>Schema</span> <span class=\"search-result-import-path\">Neo4Jay/lib/schema.js</span>",
    "class"
  ],
  [
    "neo4jay/lib/errors.js~validationerror",
    "class/lib/errors.js~ValidationError.html",
    "<span>ValidationError</span> <span class=\"search-result-import-path\">Neo4Jay/lib/errors.js</span>",
    "class"
  ],
  [
    "neo4jay/lib/relations/belongstoone.js~belongstoone",
    "class/lib/relations/belongsToOne.js~belongsToOne.html",
    "<span>belongsToOne</span> <span class=\"search-result-import-path\">Neo4Jay/lib/relations/belongsToOne.js</span>",
    "class"
  ],
  [
    "neo4jay/lib/relations/index.js~belongstoone",
    "function/index.html#static-function-belongsToOne",
    "<span>belongsToOne</span> <span class=\"search-result-import-path\">Neo4Jay/lib/relations/index.js</span>",
    "function"
  ],
  [
    "neo4jay/lib/relations/hasmany.js~hasmany",
    "class/lib/relations/hasMany.js~hasMany.html",
    "<span>hasMany</span> <span class=\"search-result-import-path\">Neo4Jay/lib/relations/hasMany.js</span>",
    "class"
  ],
  [
    "neo4jay/lib/relations/index.js~hasmany",
    "function/index.html#static-function-hasMany",
    "<span>hasMany</span> <span class=\"search-result-import-path\">Neo4Jay/lib/relations/index.js</span>",
    "function"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~audiocontext",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~AudioContext",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "lib/cypher.js",
    "file/lib/cypher.js.html",
    "lib/cypher.js",
    "file"
  ],
  [
    "lib/cypher.js~cypher#auth",
    "class/lib/cypher.js~Cypher.html#instance-member-auth",
    "lib/cypher.js~Cypher#auth",
    "member"
  ],
  [
    "lib/cypher.js~cypher#constructor",
    "class/lib/cypher.js~Cypher.html#instance-constructor-constructor",
    "lib/cypher.js~Cypher#constructor",
    "method"
  ],
  [
    "lib/cypher.js~cypher#cypher",
    "class/lib/cypher.js~Cypher.html#instance-method-cypher",
    "lib/cypher.js~Cypher#cypher",
    "method"
  ],
  [
    "lib/cypher.js~cypher#headers",
    "class/lib/cypher.js~Cypher.html#instance-member-headers",
    "lib/cypher.js~Cypher#headers",
    "member"
  ],
  [
    "lib/cypher.js~cypher#http",
    "class/lib/cypher.js~Cypher.html#instance-method-http",
    "lib/cypher.js~Cypher#http",
    "method"
  ],
  [
    "lib/cypher.js~cypher#url",
    "class/lib/cypher.js~Cypher.html#instance-member-url",
    "lib/cypher.js~Cypher#url",
    "member"
  ],
  [
    "lib/errors.js",
    "file/lib/errors.js.html",
    "lib/errors.js",
    "file"
  ],
  [
    "lib/errors.js~notfounderror#constructor",
    "class/lib/errors.js~NotFoundError.html#instance-constructor-constructor",
    "lib/errors.js~NotFoundError#constructor",
    "method"
  ],
  [
    "lib/errors.js~notfounderror#message",
    "class/lib/errors.js~NotFoundError.html#instance-member-message",
    "lib/errors.js~NotFoundError#message",
    "member"
  ],
  [
    "lib/errors.js~validationerror#constructor",
    "class/lib/errors.js~ValidationError.html#instance-constructor-constructor",
    "lib/errors.js~ValidationError#constructor",
    "method"
  ],
  [
    "lib/errors.js~validationerror#payload",
    "class/lib/errors.js~ValidationError.html#instance-member-payload",
    "lib/errors.js~ValidationError#payload",
    "member"
  ],
  [
    "lib/index.js",
    "file/lib/index.js.html",
    "lib/index.js",
    "file"
  ],
  [
    "lib/model.js",
    "file/lib/model.js.html",
    "lib/model.js",
    "file"
  ],
  [
    "lib/model.js~model.compile",
    "class/lib/model.js~Model.html#static-method-compile",
    "lib/model.js~Model.compile",
    "method"
  ],
  [
    "lib/node.js",
    "file/lib/node.js.html",
    "lib/node.js",
    "file"
  ],
  [
    "lib/node.js~node#base",
    "class/lib/node.js~Node.html#instance-member-base",
    "lib/node.js~Node#base",
    "member"
  ],
  [
    "lib/node.js~node#constructor",
    "class/lib/node.js~Node.html#instance-constructor-constructor",
    "lib/node.js~Node#constructor",
    "method"
  ],
  [
    "lib/node.js~node#db",
    "class/lib/node.js~Node.html#instance-member-db",
    "lib/node.js~Node#db",
    "member"
  ],
  [
    "lib/node.js~node#model",
    "class/lib/node.js~Node.html#instance-member-model",
    "lib/node.js~Node#model",
    "member"
  ],
  [
    "lib/node.js~node#modelname",
    "class/lib/node.js~Node.html#instance-member-modelName",
    "lib/node.js~Node#modelName",
    "member"
  ],
  [
    "lib/node.js~node#schema",
    "class/lib/node.js~Node.html#instance-member-schema",
    "lib/node.js~Node#schema",
    "member"
  ],
  [
    "lib/node.js~node#selected",
    "class/lib/node.js~Node.html#instance-member-selected",
    "lib/node.js~Node#selected",
    "member"
  ],
  [
    "lib/node.js~node#tojson",
    "class/lib/node.js~Node.html#instance-method-toJSON",
    "lib/node.js~Node#toJSON",
    "method"
  ],
  [
    "lib/relations/belongstoone.js",
    "file/lib/relations/belongsToOne.js.html",
    "lib/relations/belongsToOne.js",
    "file"
  ],
  [
    "lib/relations/belongstoone.js~belongstoone#associationtype",
    "class/lib/relations/belongsToOne.js~belongsToOne.html#instance-member-associationType",
    "lib/relations/belongsToOne.js~belongsToOne#associationType",
    "member"
  ],
  [
    "lib/relations/belongstoone.js~belongstoone#constructor",
    "class/lib/relations/belongsToOne.js~belongsToOne.html#instance-constructor-constructor",
    "lib/relations/belongsToOne.js~belongsToOne#constructor",
    "method"
  ],
  [
    "lib/relations/belongstoone.js~belongstoone#name",
    "class/lib/relations/belongsToOne.js~belongsToOne.html#instance-member-name",
    "lib/relations/belongsToOne.js~belongsToOne#name",
    "member"
  ],
  [
    "lib/relations/belongstoone.js~belongstoone#options",
    "class/lib/relations/belongsToOne.js~belongsToOne.html#instance-member-options",
    "lib/relations/belongsToOne.js~belongsToOne#options",
    "member"
  ],
  [
    "lib/relations/belongstoone.js~belongstoone#schema",
    "class/lib/relations/belongsToOne.js~belongsToOne.html#instance-member-schema",
    "lib/relations/belongsToOne.js~belongsToOne#schema",
    "member"
  ],
  [
    "lib/relations/belongstoone.js~belongstoone#singlerelationsship",
    "class/lib/relations/belongsToOne.js~belongsToOne.html#instance-member-singleRelationsship",
    "lib/relations/belongsToOne.js~belongsToOne#singleRelationsship",
    "member"
  ],
  [
    "lib/relations/belongstoone.js~belongstoone#target",
    "class/lib/relations/belongsToOne.js~belongsToOne.html#instance-member-target",
    "lib/relations/belongsToOne.js~belongsToOne#target",
    "member"
  ],
  [
    "lib/relations/hasmany.js",
    "file/lib/relations/hasMany.js.html",
    "lib/relations/hasMany.js",
    "file"
  ],
  [
    "lib/relations/hasmany.js~hasmany#constructor",
    "class/lib/relations/hasMany.js~hasMany.html#instance-constructor-constructor",
    "lib/relations/hasMany.js~hasMany#constructor",
    "method"
  ],
  [
    "lib/relations/hasmany.js~hasmany#name",
    "class/lib/relations/hasMany.js~hasMany.html#instance-member-name",
    "lib/relations/hasMany.js~hasMany#name",
    "member"
  ],
  [
    "lib/relations/hasmany.js~hasmany#options",
    "class/lib/relations/hasMany.js~hasMany.html#instance-member-options",
    "lib/relations/hasMany.js~hasMany#options",
    "member"
  ],
  [
    "lib/relations/hasmany.js~hasmany#relationshiptype",
    "class/lib/relations/hasMany.js~hasMany.html#instance-member-relationshipType",
    "lib/relations/hasMany.js~hasMany#relationshipType",
    "member"
  ],
  [
    "lib/relations/hasmany.js~hasmany#schema",
    "class/lib/relations/hasMany.js~hasMany.html#instance-member-schema",
    "lib/relations/hasMany.js~hasMany#schema",
    "member"
  ],
  [
    "lib/relations/hasmany.js~hasmany#singlerelationsship",
    "class/lib/relations/hasMany.js~hasMany.html#instance-member-singleRelationsship",
    "lib/relations/hasMany.js~hasMany#singleRelationsship",
    "member"
  ],
  [
    "lib/relations/hasmany.js~hasmany#target",
    "class/lib/relations/hasMany.js~hasMany.html#instance-member-target",
    "lib/relations/hasMany.js~hasMany#target",
    "member"
  ],
  [
    "lib/relations/index.js",
    "file/lib/relations/index.js.html",
    "lib/relations/index.js",
    "file"
  ],
  [
    "lib/schema.js",
    "file/lib/schema.js.html",
    "lib/schema.js",
    "file"
  ],
  [
    "lib/schema.js~schema#constructor",
    "class/lib/schema.js~Schema.html#instance-constructor-constructor",
    "lib/schema.js~Schema#constructor",
    "method"
  ],
  [
    "lib/schema.js~schema#methods",
    "class/lib/schema.js~Schema.html#instance-member-methods",
    "lib/schema.js~Schema#methods",
    "member"
  ],
  [
    "lib/schema.js~schema#relationships",
    "class/lib/schema.js~Schema.html#instance-member-relationships",
    "lib/schema.js~Schema#relationships",
    "member"
  ],
  [
    "lib/schema.js~schema#relationsship",
    "class/lib/schema.js~Schema.html#instance-method-relationsship",
    "lib/schema.js~Schema#relationsship",
    "method"
  ],
  [
    "lib/schema.js~schema#validate",
    "class/lib/schema.js~Schema.html#instance-method-validate",
    "lib/schema.js~Schema#validate",
    "method"
  ]
]